version: '3.1'
services:
  stats-server:
    build: ./stats
    container_name: stats
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats_db:5432/stats_db
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER-PORT=9090
    depends_on:
      - stats_db
      - zookeeper
      - kafka

  stats_db:
    image: postgres:14-alpine
    container_name: stats_db
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_DB=stats_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./server
    container_name: server
    ports:
      - "8080:8080"

    environment:
      - STATS-SERVER_URL=http://localhost:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm_db:5432/ewm_db
      - SPRING_DATASOURCE_USER=ewm
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER-PORT=8080
    depends_on:
      - ewm_db
      - stats-server
      - zookeeper
      - kafka

  ewm_db:
    image: postgres:14-alpine
    container_name: ewm_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ewm_db
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=password

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
      image: 'bitnami/kafka:latest'
      ports:
        - '9092:9092'
      environment:
        - KAFKA_BROKER_ID=1
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
      depends_on:
        - zookeeper
