version: '3.1'
services:
  stats-server:
    build: ./stats
    container_name: stats
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats_db:5432/stats_db
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER-PORT=9090
    depends_on:
      - stats_db
      - zookeeper
      - broker

  stats_db:
    image: postgres:14-alpine
    container_name: stats_db
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_DB=stats_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./server
    container_name: server
    ports:
      - "8080:8080"

    environment:
      - STATS-SERVER_URL=http://localhost:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm_db:5432/ewm_db
      - SPRING_DATASOURCE_USER=ewm
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER-PORT=8080
    depends_on:
      - ewm_db
      - stats-server
      - zookeeper
      - broker

  ewm_db:
    image: postgres:14-alpine
    container_name: ewm_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ewm_db
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=password

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    user: "0:0"
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./zoo/data:/var/lib/zookeeper/data
      - ./zoo/log:/var/lib/zookeeper/log

  broker:
      image: confluentinc/cp-kafka:latest
      hostname: broker
      container_name: broker
      user: "0:0"
      depends_on:
        - zookeeper
      ports:
        - "9092:9092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      volumes:
        - ./broker/data:/var/lib/kafka/data
