version: '3.1'
services:
  stats-server:
    build: ./stats
    container_name: stats
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats_db:5444/stats_db
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER-PORT=9090
    depends_on:
      - stats-db

  stats-db:
    image: postgres:14-alpine
    container_name: stats_db
    ports:
      - "5444:5444"
    environment:
      - POSTGRES_DB=stats_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./server
    container_name: server
    ports:
      - "8080:8080"

    environment:
      - STATS-SERVER_URL=http://localhost:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm_db:5432/ewm_db
      - SPRING_DATASOURCE_USER=ewm
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER-PORT=8080
    depends_on:
      - ewm-db
      - stats-server

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ewm_db
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=password
